# **Analysis on Mortgage Based Securities Prepayment Ability**
Task -EDA on  Dataset



#### **Import libraries and load dataset**






In [189]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [190]:
df=pd.read_csv('LoanExport.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (18) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [191]:
df.head()

CreditScore  FirstPaymentDate  ... MonthsDelinquent  MonthsInRepayment
0            0            199902  ...                0                 52
1            0            199902  ...                0                144
2            0            199902  ...                0                 67
3            0            199902  ...                0                 35
4            0            199902  ...                0                 54

[5 rows x 28 columns]

In [192]:
df.tail()

CreditScore  FirstPaymentDate  ... MonthsDelinquent  MonthsInRepayment
291446          839            199903  ...                0                 12
291447          840            200210  ...                0                 53
291448          840            200304  ...                0                 38
291449          845            199904  ...                0                 32
291450          849            199903  ...                0                 29

[5 rows x 28 columns]

In [193]:
df.shape

(291451, 28)

In [194]:
df.columns

Index(['CreditScore', 'FirstPaymentDate', 'FirstTimeHomebuyer', 'MaturityDate',
       'MSA', 'MIP', 'Units', 'Occupancy', 'OCLTV', 'DTI', 'OrigUPB', 'LTV',
       'OrigInterestRate', 'Channel', 'PPM', 'ProductType', 'PropertyState',
       'PropertyType', 'PostalCode', 'LoanSeqNum', 'LoanPurpose',
       'OrigLoanTerm', 'NumBorrowers', 'SellerName', 'ServicerName',
       'EverDelinquent', 'MonthsDelinquent', 'MonthsInRepayment'],
      dtype='object')

#### **Checking the types of data**

In [195]:
df.dtypes

CreditScore             int64
FirstPaymentDate        int64
FirstTimeHomebuyer     object
MaturityDate            int64
MSA                    object
MIP                     int64
Units                   int64
Occupancy              object
OCLTV                   int64
DTI                     int64
OrigUPB                 int64
LTV                     int64
OrigInterestRate      float64
Channel                object
PPM                    object
ProductType            object
PropertyState          object
PropertyType           object
PostalCode             object
LoanSeqNum             object
LoanPurpose            object
OrigLoanTerm            int64
NumBorrowers           object
SellerName             object
ServicerName           object
EverDelinquent          int64
MonthsDelinquent        int64
MonthsInRepayment       int64
dtype: object

In [196]:
df.nunique()

CreditScore              370
FirstPaymentDate          66
FirstTimeHomebuyer         3
MaturityDate              96
MSA                      392
MIP                       37
Units                      5
Occupancy                  3
OCLTV                    102
DTI                       66
OrigUPB                  375
LTV                       97
OrigInterestRate         254
Channel                    4
PPM                        3
ProductType                1
PropertyState             53
PropertyType               7
PostalCode              1767
LoanSeqNum            291451
LoanPurpose                3
OrigLoanTerm              61
NumBorrowers               3
SellerName                20
ServicerName              20
EverDelinquent             2
MonthsDelinquent         174
MonthsInRepayment        212
dtype: int64

 #### **Dropping the missing or null values.**


In [197]:
missing_values_count=df.isnull().sum()
missing_values_count

CreditScore               0
FirstPaymentDate          0
FirstTimeHomebuyer        0
MaturityDate              0
MSA                       0
MIP                       0
Units                     0
Occupancy                 0
OCLTV                     0
DTI                       0
OrigUPB                   0
LTV                       0
OrigInterestRate          0
Channel                   0
PPM                       0
ProductType               0
PropertyState             0
PropertyType              0
PostalCode                0
LoanSeqNum                0
LoanPurpose               0
OrigLoanTerm              0
NumBorrowers              0
SellerName            24994
ServicerName              0
EverDelinquent            0
MonthsDelinquent          0
MonthsInRepayment         0
dtype: int64

#### **Dropping irrelevant columns**


In [198]:
df=df.drop(['FirstPaymentDate','MaturityDate','MSA','Occupancy','Channel','PPM','ProductType','PropertyState','PropertyType',
            'PostalCode','LoanSeqNum','LoanPurpose','NumBorrowers','SellerName','ServicerName'],axis=1)

  


#### **Dropping the rest rows with NA values**

In [199]:
df.dropna(inplace=True)
df.info()
df.shape


<class 'pandas.core.frame.DataFrame'>
Int64Index: 291451 entries, 0 to 291450
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   CreditScore         291451 non-null  int64  
 1   FirstTimeHomebuyer  291451 non-null  object 
 2   MIP                 291451 non-null  int64  
 3   Units               291451 non-null  int64  
 4   OCLTV               291451 non-null  int64  
 5   DTI                 291451 non-null  int64  
 6   OrigUPB             291451 non-null  int64  
 7   LTV                 291451 non-null  int64  
 8   OrigInterestRate    291451 non-null  float64
 9   OrigLoanTerm        291451 non-null  int64  
 10  EverDelinquent      291451 non-null  int64  
 11  MonthsDelinquent    291451 non-null  int64  
 12  MonthsInRepayment   291451 non-null  int64  
dtypes: float64(1), int64(11), object(1)
memory usage: 31.1+ MB


(291451, 13)

#### Converting Data into Range

In [200]:
df.CreditScore.unique()

array([  0, 335, 342, 363, 366, 370, 375, 391, 396, 445, 462, 466, 471,
       476, 477, 478, 479, 481, 482, 483, 485, 486, 487, 489, 490, 491,
       492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504,
       505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517,
       518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530,
       531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543,
       544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556,
       557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569,
       570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582,
       583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595,
       596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608,
       609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621,
       622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634,
       635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 64

CreditScore contains a 0 which the data definition states is actually 850.Converting  all 0's to 850


In [201]:
df['CreditScore'] = np.where(df['CreditScore'] == 0, 850, df['CreditScore'])
df.CreditScore.unique()

array([850, 335, 342, 363, 366, 370, 375, 391, 396, 445, 462, 466, 471,
       476, 477, 478, 479, 481, 482, 483, 485, 486, 487, 489, 490, 491,
       492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504,
       505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517,
       518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530,
       531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543,
       544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556,
       557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569,
       570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582,
       583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595,
       596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608,
       609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621,
       622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634,
       635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 64

 Create new variable for CREDIT_SCORE.
 New values = Poor (0-650), Fair (650-700), Good (700-750), Excellent (750-900)

In [202]:
df['CreditRange'] = pd.cut(df.CreditScore,[550,650,700,750,850],4,labels=[1,2,3,4])
df.CreditScore.value_counts()

748    2567
734    2537
747    2456
753    2427
764    2419
       ... 
391       1
396       1
445       1
462       1
849       1
Name: CreditScore, Length: 370, dtype: int64

In [203]:
df.FirstTimeHomebuyer.unique()

array(['N', 'X', 'Y'], dtype=object)

FirstTimeHomebuyer contains X's which stand for unknowns,i.e. Nulls. 
Need to remove all rows that do not have a valid answer, Y/N, as they are not useful to our research.


In [204]:
df = df[df.FirstTimeHomebuyer != 'X']
df.FirstTimeHomebuyer.unique()

array(['N', 'Y'], dtype=object)

In [205]:
# Check the row and column count of our dataset to see how many rows were just removed.
df.shape

(213436, 14)

In [206]:
# Count values in FIRST_TIME_HOMEBUYER_FLAG
df['FirstTimeHomebuyer'].value_counts()

N    184154
Y     29282
Name: FirstTimeHomebuyer, dtype: int64

In [207]:
# Convert Y/N to 1 or 0 and then count values again to ensure they match
df['FirstTimeHomebuyer'] = np.where(df['FirstTimeHomebuyer'] == 'Y', 1, 0)
df['FirstTimeHomebuyer'].value_counts()

0    184154
1     29282
Name: FirstTimeHomebuyer, dtype: int64

In [208]:
df.OCLTV.unique()

array([ 89,  73,  75,  76,  78,  90,  95,  80,  77,  85,  93,  70,  74,
        79,  72,  62,  44,  32,  64,  91,  53,  69,  60,  54,  52,  84,
        68,  36,  55,  96,  97,  46,  58,  63,  83,  87,  94,  48,  50,
        51,  67,  86,  81,  66,  71,  82,  88,  26,  59,  57,  61,  30,
        24,  34,  37,  42,  65,  31, 100,   7,  38,  39,  16,  41,  33,
        92,  40,  35,  56,  22,  28,  43,  47,  49,  98,  29,  45,  25,
       103,  10,  18,  23,  20,  15, 102, 101,  14,  21,  27, 105,  19,
         8,   0, 104,  17, 110,  99,  12,   6,  13,   9,  11])

In [209]:
df.Units.unique()

array([1, 2, 3, 4, 0])

In [210]:
df['Units'].value_counts()

1    209501
2      3242
3       346
4       345
0         2
Name: Units, dtype: int64

In [211]:
# Units = 0 means that we do not have data on this so it is really a Null value, removing those rows.
df = df[df.Units != 0]
df['Units'].value_counts()

1    209501
2      3242
3       346
4       345
Name: Units, dtype: int64

In [212]:
df.MIP.unique()

array([25,  0, 30, 12, 35, 29, 17, 18, 20, 22,  6, 14, 33, 16, 52, 36, 28,
       11, 45, 27, 10, 50, 47,  7, 24, 15, 37, 32, 26,  1, 13, 21, 23, 55,
        4])

In [213]:
# Find values in DTI
df.DTI.unique()

array([27, 17, 16, 14, 18, 40, 21, 38, 19, 23, 45, 28, 29, 15, 43, 25, 24,
       26, 20, 35, 46, 39, 33, 48, 30, 31, 22, 56, 32, 12,  6, 37, 36, 42,
       34, 11, 41,  8, 44, 55,  0, 51, 10,  7, 47,  9, 13, 65, 54,  2, 53,
       57,  5,  3,  4, 50, 59, 49, 52, 64, 60, 58,  1, 61, 62, 63])

In [214]:
# Find values in OrigUPB
df.OrigUPB.unique()

array([117000, 109000,  88000, 160000, 207000, 111000,  55000,  35000,
       126000, 200000,  70000,  93000,  79000,  54000,  80000, 231000,
       145000, 187000, 148000,  90000,  65000,  86000, 122000, 157000,
        94000,  63000,  50000, 100000, 191000, 204000, 222000, 189000,
        57000, 202000, 137000,  56000, 140000,  18000,  76000,  77000,
       151000, 118000, 182000,  98000,  89000, 172000,  82000, 240000,
       102000, 173000,  51000, 169000, 101000, 152000, 141000,  47000,
       128000, 133000, 135000, 115000, 144000, 146000, 212000, 176000,
       214000, 190000, 227000,  99000,  83000,  49000,  29000, 124000,
       132000, 150000, 300000,  95000, 149000, 162000, 226000, 110000,
       112000, 219000, 236000,  67000, 195000, 164000, 198000,  60000,
       194000, 147000, 104000,  72000, 183000, 154000, 179000,  66000,
       210000,  46000,  96000, 225000, 156000,  45000, 235000, 113000,
       139000,  74000,  68000,  69000, 238000, 142000,  73000,  48000,
      

In [215]:
# Find values in LTV
df.LTV.unique()

array([ 89,  73,  75,  76,  78,  90,  95,  80,  77,  85,  93,  70,  74,
        79,  72,  62,  44,  32,  64,  91,  53,  69,  60,  54,  52,  84,
        68,  36,  55,  96,  97,  46,  58,  63,  83,  87,  94,  48,  50,
        51,  67,  86,  81,  66,  71,  82,  88,  26,  59,  57,  61,  30,
        24,  34,  37,  42,  65,  31,   7,  38,  39,  16,  41,  33,  92,
        40,  35,  56,  22,  28,  43,  47, 100,  49,  98,  29,  45,  25,
        10,  18,  23,  20,  15, 103,  14,  21,  27,  19,   8,   0,  17,
        12,   6,  13,   9,  11])

In [216]:
# Create new variable for LTV Range
df['LTV_range'] = pd.cut(df.LTV,[0,25,50,1000],3,labels=['Low','Medium','High'])
df.LTV_range.unique()

['High', 'Medium', 'Low', NaN]
Categories (3, object): ['Low' < 'Medium' < 'High']

In [217]:
# Find values in OrigInterestRate
df.OrigInterestRate.unique()

array([ 6.75 ,  6.5  ,  6.875,  7.125,  7.   ,  7.25 ,  6.625,  7.75 ,
        7.2  ,  7.5  ,  7.625,  7.875,  6.25 ,  8.125,  7.15 ,  7.375,
        6.375,  8.75 ,  7.1  ,  7.05 ,  6.95 ,  8.   ,  8.625,  8.375,
        8.5  ,  6.125,  6.   ,  5.875,  8.25 ,  8.99 ,  5.625,  9.   ,
        5.125,  5.25 ,  9.125,  6.99 ,  5.375,  8.365,  8.875,  6.975,
        7.3  ,  7.313,  9.625,  9.25 ,  5.75 ,  7.85 ,  8.695,  4.875,
        7.775,  7.29 ,  7.405,  9.5  ,  9.375,  9.75 ,  7.13 ,  5.99 ,
        6.999,  7.055,  7.09 ,  6.785,  7.08 ,  7.025,  7.7  ,  7.58 ,
       10.5  ,  7.55 ,  7.445,  9.875,  6.85 ,  6.925,  6.9  ,  8.37 ,
        7.095,  7.19 ,  7.456,  7.675,  9.675,  7.475,  7.22 ,  7.17 ,
        8.7  ,  7.301,  8.9  , 10.   ,  5.5  ,  6.62 ,  7.325, 10.375,
        7.8  ,  7.4  , 10.85 ,  7.185,  7.245, 11.5  ,  6.94 ,  6.87 ,
        7.65 ,  7.312,  7.28 ,  7.39 ,  7.07 ,  7.43 ,  7.48 ,  6.88 ,
        8.45 ,  6.895,  5.   ,  6.3  ,  7.49 ,  6.8  ,  6.63 ,  8.05 ,
      

In [218]:
# Find values in OrigLoanTerm
df.OrigLoanTerm.unique()

array([360, 345, 306, 335, 322, 327, 358, 355, 356, 354, 346, 344, 348,
       313, 316, 353, 319, 332, 336, 338, 312, 328, 351, 333, 359, 331,
       337, 334, 357, 330, 350, 341, 343, 325, 326, 324, 347, 352, 329,
       339, 309, 317, 349, 342, 304, 310, 340, 301, 305, 315, 323, 321,
       320, 302, 314, 318, 308, 303, 307, 361, 311])

In [219]:
# Find values in EverDelinquent
df.EverDelinquent.unique()

array([0, 1])

In [220]:
# Find values in MonthsInRepayment
df.MonthsInRepayment.unique()

array([ 52, 144,  67,  35,  54,  42,  44,  64, 212,  37,  47,  53,  55,
        66,  26,  38,  36,  39,  40,  11, 176,  46, 197, 210,  56, 118,
        63,  24,  28,  91,  50,  22, 211, 199,  23,  30, 125,  41,  76,
        49,  18,  19,  43,  60,  83,  95,  29,  45,  13,   6,  48,  62,
        14,  15, 111,  51,  17,  75,  58,  27,  10,  31, 133, 165, 156,
        33,  68, 205,  57, 159,  81, 191, 194, 114,  59, 100, 134, 128,
        71,   7,  65,  74,  79, 174, 195, 151,  34, 149,  21,  12, 137,
       130,  69,  70, 173, 166,  61, 160,  20, 178,   3,  72, 147,   2,
        32, 164, 139, 108, 148,  92, 209, 102,  87,  94,  73, 123,  16,
       142,   1, 172, 109, 141, 175, 103, 168,   5, 155, 177, 158, 138,
        25, 110,  98,  84, 136,   8, 121, 179,   4, 154, 161, 157, 150,
        80, 170,  77,   9, 183,  93, 143, 162, 126,  89, 208, 184,  82,
       145, 117, 101, 122, 107, 193,  85,  78, 169, 104, 131, 140, 163,
       112, 206, 135, 132, 124, 186, 127, 189, 190, 198, 192, 16

In [221]:
df.isnull().sum()    
   # After dropping the values

CreditScore             0
FirstTimeHomebuyer      0
MIP                     0
Units                   0
OCLTV                   0
DTI                     0
OrigUPB                 0
LTV                     0
OrigInterestRate        0
OrigLoanTerm            0
EverDelinquent          0
MonthsDelinquent        0
MonthsInRepayment       0
CreditRange           526
LTV_range               3
dtype: int64

In [222]:
df=df.dropna()

In [223]:
df.shape

(212905, 15)

#### Creating new features in dataset

In [224]:
# Create new variable Repay range
df['Repay_range'] = pd.cut(df.MonthsInRepayment,[0,48,96,144,192,240],5,
                           labels=['0-4yrs','4-8yrs','8-12yrs', '12-16yrs', '16-20yrs'])
print('Repay_range values:', df.Repay_range.unique())
df['Repay_range'].value_counts()

Repay_range values: ['4-8yrs', '8-12yrs', '0-4yrs', '16-20yrs', '12-16yrs']
Categories (5, object): ['0-4yrs' < '4-8yrs' < '8-12yrs' < '12-16yrs' < '16-20yrs']


0-4yrs      108653
4-8yrs       73488
8-12yrs      13885
12-16yrs      8728
16-20yrs      8151
Name: Repay_range, dtype: int64

 #### **Renaming the columns**

In [231]:
df = df.rename(columns={"CreditScore": "CS", "FirstTimeHomebuyer": "IsFirstTime"}) 
df.head(5)

CS  IsFirstTime  MIP  ...  CreditRange  LTV_range  Repay_range
0  850            0   25  ...            4       High       4-8yrs
1  850            0    0  ...            4       High      8-12yrs
2  850            0    0  ...            4       High       4-8yrs
3  850            0    0  ...            4       High       0-4yrs
4  850            0    0  ...            4       High       4-8yrs

[5 rows x 16 columns]

#### Final check of our dataframe before moving on.


In [232]:
df.shape



(212905, 16)

In [233]:
df.isnull().values.any()

False

#### Grouping Data

In [234]:
df_grouped = df.groupby(by=['CreditRange'])
df_grouped = df.groupby(by=['CreditRange','LTV_range'])
df_grouped = df.groupby(by=['Repay_range'])
df_grouped = df.groupby(by=['CreditRange','IsFirstTime','LTV_range','Repay_range'])
df_grouped.describe()

CS              ... MonthsInRepayment       
                                                count        mean  ...               75%    max
CreditRange IsFirstTime LTV_range Repay_range                      ...                         
1           0           Low       0-4yrs         17.0  627.529412  ...              41.0   46.0
                                  4-8yrs         13.0  635.384615  ...              65.0   93.0
                                  8-12yrs         3.0  637.333333  ...             126.5  135.0
                                  12-16yrs        2.0  608.000000  ...             181.0  189.0
                                  16-20yrs        1.0  631.000000  ...             193.0  193.0
...                                               ...         ...  ...               ...    ...
4           1           High      0-4yrs       3064.0  771.980418  ...              44.0   48.0
                                  4-8yrs       2211.0  773.217096  ...              63.0   96.0
                                  8-12yrs       476.0  775.466387  ...             132.0  144.0
                                  12-16yrs      315.0  778.028571  ...             176.0  191.0
                                  16-20yrs      241.0  784.340249  ...             211.0  212.0

[110 rows x 96 columns]

In [240]:
df_imputed = df_grouped.transform(lambda grp: grp.fillna(grp.median()))
df_imputed[['IsFirstTime','EverDelinquent']] = df[['IsFirstTime','EverDelinquent']]
df.dropna(inplace=True)

In [241]:
# Slicing the CreditScore
df_imputed['CreditRange'] = pd.cut(df_imputed.CS,[550,650,700,750,1e6],4,labels=[1,2,3,4]) # this creates a new variable
df_imputed.CreditRange.describe()

count     212905
unique         4
top            3
freq       72678
Name: CreditRange, dtype: int64

In [242]:
# Slicing the LTV
df_imputed['LTV_range'] = pd.cut(df_imputed.LTV,[0,25,50,110],3,labels=['low','medium','high']) # this creates a new variable
df_imputed.LTV_range.describe()

count     212905
unique         3
top         high
freq      198358
Name: LTV_range, dtype: object

In [243]:
# Taking slices of the MonthsInRepayment
df_imputed['Repay_range'] = pd.cut(df_imputed.MonthsInRepayment,[0,48,96,144,192,240],5,labels=['0-4yrs','4-8yrs','8-12yrs', '12-16yrs', '16-20yrs'])
df_imputed.Repay_range.describe()

count     212905
unique         5
top       0-4yrs
freq      108653
Name: Repay_range, dtype: object

In [244]:
df_imputed.head()
df_imputed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 212905 entries, 0 to 291450
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype   
---  ------             --------------   -----   
 0   CS                 212905 non-null  int64   
 1   MIP                212905 non-null  int64   
 2   Units              212905 non-null  int64   
 3   OCLTV              212905 non-null  int64   
 4   DTI                212905 non-null  int64   
 5   OrigUPB            212905 non-null  int64   
 6   LTV                212905 non-null  int64   
 7   OrigInterestRate   212905 non-null  float64 
 8   OrigLoanTerm       212905 non-null  int64   
 9   EverDelinquent     212905 non-null  int64   
 10  MonthsDelinquent   212905 non-null  int64   
 11  MonthsInRepayment  212905 non-null  int64   
 12  IsFirstTime        212905 non-null  int64   
 13  CreditRange        212905 non-null  category
 14  LTV_range          212905 non-null  category
 15  Repay_range        212905 non-null